#!/usr/bin/env dash
if [ -e ".legit" ]
then
        flag=`ls ".legit/.branches"|grep "\*$"`
        if [ -d ".legit/.branches" -a ! "$flag" = ""  ]
        then
                for file in ".legit/.branches"/*
                do  
                        temp=`echo $file|grep '[\*]$'`
                        if [ ! "$temp" = "" ]
                        then
                                repo_dir=$temp
                        fi  
                done
        else
                repo_dir=".legit"
        fi  
else
        echo "legit-add: error: no .legit directory containing legit repository exists"
        exit 1
fi




cat ./$repo_dir/.log|sort -r

#this file print the log file in descending order
