#!/usr/bin/env dash
if [ -e ".legit" ]
then
    for file in ".legit/.branches/"*
    do  
        temp=`echo "$file"|grep '[\*]$'`
        if [ ! "$temp" = "" ]
        then
            repo_dir=$temp
        fi  
    done

    if [  "$repo_dir" = ""  ]
    then
        repo_dir=".legit"
    fi  
else
    echo "legit-log: error: no .legit directory containing legit repository exists"
    exit 1
fi


cat ./$repo_dir/.log|sort -r

#this file print the log file in descending order
